name: Build & Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.7
          channel: stable

      - name: Install dependencies
        run: make install

      - name: Build APK
        run: make build-apk

      - name: Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk \
             deskconn-mobile-app.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Deskconn Mobile – Latest
          files: deskconn-mobile-app.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
