name: Build & Release APK

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.38.7
          channel: stable

      - name: Install dependencies
        run: make install

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/deskconn-release-key.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=deskconn-release-key.jks
          EOF

      - name: Build APK
        run: flutter build apk --no-tree-shake-icons --build-number=${{ github.run_number }}

      - name: Prepare APK for Release
        run: cp build/app/outputs/flutter-apk/app-release.apk deskconn-mobile-app.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Deskconn Mobile – Release ${{ github.run_number }}
          body: "Changes: ${{ github.event.head_commit.message }}"
          files: deskconn-mobile-app.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Discord
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"New Deskconn Mobile Release successful\n [Download APK](https://github.com/${{ github.repository }}/releases/tag/v${{ github.run_number }})\nUpdate: *${{ steps.commit.outputs.message }}*\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
